version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  reviewers:
  - Chaostheorie
  ignore:
  - dependency-name: pytest
    versions:
    - 6.2.1
